### ISSUE TITLE
banana-rdf support and GoogleSummerOfCode

### ISSUE THREAD

**Issue by antonkulaga** [labra/ShExcala#26]
Soon there will be a posibility to submit application to [Google Summer of Code](https://developers.google.com/open-source/gsoc/timeline)
I had a conversation with @InTheNow and we came to a point that Shacl (ShEx) support can be a good project idea for GSoC from banana-rdf. But, such kind of project is not possible without your involvement as somebody will have to mentor students who agreed to take this task

**Comment by labra** [comment]
That would be indeed a very nice project and I would be interested to involve myself as a mentor on it. I will contact you to ask more details about this possibility by email.

**Comment by InTheNow** [comment]
@labra I also sent you a private chat on gitter a while back, too

**Comment by labra** [comment]
Sorry, I didn't notice it...I was a bit overloaded with gitter messages from some chat rooms that I was not very interested, and I used to delete messages from gitter without reading them...could you send it to me again?

**Comment by labra** [comment]
I am afraid that the deadline for the GSOC has passed. I will close the issue by now, although I would be very interested in any collaboration in this direction.
